### PR TITLE
build against libblas and liblapack

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

See https://conda-forge.org/docs/maintainer/knowledge_base.html#blas. To my understanding, when the package is built against liblapack, it can be run with any variant of LAPACK (openblas, mkl, etc).

See also https://github.com/conda-forge/dftbplus-feedstock/blob/main/recipe/meta.yaml#L60

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
It seems not working at all, though.

**Comment by caic99** [comment]
> It seems not working at all, though.

@njzjz ABACUS requires Scalapack, which is not explicitly listed out as requirement in recipe, but contained in OpenBLAS.

Maybe trying to use mkl-devel would be a better approach.

**Comment by njzjz** [comment]
> Maybe trying to use mkl-devel would be a better approach.

@caic99 It seems openblas is hardcoded in https://github.com/deepmodeling/abacus-develop/blob/e2322fa0983be5f57e48c84a77c3565771aa2037/cmake/FindLAPACK.cmake#L9

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Comment by njzjz** [comment]
@conda-forge-admin rerender

**Pull request merged**
