### PR TITLE
Add libri building

### PR DESCRIPTION
**Pull request by caic99**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

@conda-forge-admin, please rerender

### CODE REVIEW

**Comment by caic99** [comment]
@njzjz I realized that conda-build retrieves the source code from the release page, which is not a git repo, failing in `git submodule init`
https://github.com/conda-forge/abacus-feedstock/blob/fa85b33ee57ffeed4a18c002e5a0f9b3cec59ed4/recipe/meta.yaml#L9-L11

Is it possible replacing with `  git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }}` following the [docs](https://conda-forge.org/docs/user/ci-skeleton.html#fill-out-recipe-meta-yaml)? Thanks.

**Comment by njzjz** [comment]
> Is it possible replacing with git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }} following the docs? Thanks.

Git sources are not recommended as checksum can not be checked.

The submodules can be manually added to the source files.

**Comment by caic99** [comment]
> > Is it possible replacing with git_url: {{ environ.get('FEEDSTOCK_ROOT', '..') }} following the docs? Thanks.
> 
> Git sources are not recommended as checksum can not be checked.
> 
> The submodules can be manually added to the source files.

I see, but this requires additional efforts. I am going to use git_url to support the new features.

**Comment by njzjz** [comment]
In https://github.com/conda-forge/conda-forge.github.io/issues/619, half of projects that links to this issue use git while the rest projects add the submodule to the source. Maybe both are ok.

But I think the best solution is to avoid using submodules in the source repository.

**Pull request merged**
