### PR TITLE
Rebuild for pytorch 2.1

### PR DESCRIPTION
**Pull request by njzjz**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
@caic99 got this error:
```
2023-11-15T20:38:38.9925019Z /home/conda/feedstock_root/build_artifacts/abacus_1700080287649/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/lib/python3.12/site-packages/torch/include/c10/util/C++17.h:27:2: error: #error You need C++17 to compile PyTorch
2023-11-15T20:38:38.9927341Z    27 | #error You need C++17 to compile PyTorch
2023-11-15T20:38:38.9927747Z       |  ^~~~~
```

Not sure why `std=c++17` flag not work:
```
2023-11-15T20:35:53.9511649Z +CXXFLAGS=-fvisibility-inlines-hidden -std=c++17 -fmessage-length=0 -march=nocona -mtune=haswell -ftree-vectorize -fPIC -fstack-protector-strong -fno-plt -O2 -ffunction-sections -pipe -isystem $PREFIX/include -fdebug-prefix-map=$SRC_DIR=/usr/local/src/conda/abacus-3.4.1 -fdebug-prefix-map=$PREFIX=/usr/local/src/conda-prefix
```

**Comment by caic99** [comment]
Hi @njzjz ,
Did pytorch bump the required C++ standart version from 14 to 17? Currently it is set to 14
https://github.com/deepmodeling/abacus-develop/blob/1144c0e1ccebfefb24160e002514a5b23778282f/CMakeLists.txt#L392-L396

**Comment by njzjz** [comment]
> Did pytorch bump the required C++ standart version from 14 to 17?

xref: https://github.com/pytorch/pytorch/pull/100557

**Comment by njzjz** [comment]
@caic99 it seems not to be working when I add a patch to change `CMAKE_CXX_STANDARD`.

**Comment by caic99** [comment]
> @caic99 it seems not to be working when I add a patch to change `CMAKE_CXX_STANDARD`.

I will try building with pytorch 2.1 locally.

**Comment by caic99** [comment]
> > @caic99 it seems not to be working when I add a patch to change `CMAKE_CXX_STANDARD`.
> 
> I will try building with pytorch 2.1 locally.

@njzjz I think checking if `CMAKE_CXX_STANDARD` has already been set to a higher value is required before setting it.

https://github.com/deepmodeling/abacus-develop/blob/baccbe3356f81c9b349582e4b02fd723d77a50d9/CMakeLists.txt#L446

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Comment by njzjz** [comment]
Some other modules do not support C++17:

```
2023-12-01T01:06:22.6125718Z In file included from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:10,
2023-12-01T01:06:22.6127875Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.h:48,
2023-12-01T01:06:22.6129740Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.hpp:9,
2023-12-01T01:06:22.6131418Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.h:95,
2023-12-01T01:06:22.6132844Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/Comm_Assemble.h:8,
2023-12-01T01:06:22.6134237Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map.h:10,
2023-12-01T01:06:22.6135716Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map_Judge.h:8,
2023-12-01T01:06:22.6137068Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.hpp:9,
2023-12-01T01:06:22.6138253Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.h:58,
2023-12-01T01:06:22.6139365Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx.h:8,
2023-12-01T01:06:22.6140417Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI.h:14,
2023-12-01T01:06:22.6141442Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI_interface.h:2,
2023-12-01T01:06:22.6142543Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_esolver/esolver_ks_lcao.h:12,
2023-12-01T01:06:22.6143718Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_hamilt_lcao/module_tddft/evolve_elec.h:6,
2023-12-01T01:06:22.6144930Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_elecstate/potentials/H_TDDFT_pw.cpp:5:
2023-12-01T01:06:22.6146971Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/MPI_Wrapper.h:85:42: error: the address of the 'ompi_datatype_t' subobject of 'ompi_mpi_char' is not a valid template argument
2023-12-01T01:06:22.6148524Z    85 |  static MPI_Type_Contiguous_Pool<MPI_CHAR> char_contiguous;
2023-12-01T01:06:22.6149094Z       |                                          ^
2023-12-01T01:06:22.6220525Z In file included from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.h:48,
2023-12-01T01:06:22.6223230Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.hpp:9,
2023-12-01T01:06:22.6224922Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.h:95,
2023-12-01T01:06:22.6226337Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/Comm_Assemble.h:8,
2023-12-01T01:06:22.6227722Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map.h:10,
2023-12-01T01:06:22.6229195Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map_Judge.h:8,
2023-12-01T01:06:22.6230546Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.hpp:9,
2023-12-01T01:06:22.6231766Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.h:58,
2023-12-01T01:06:22.6232878Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx.h:8,
2023-12-01T01:06:22.6233888Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI.h:14,
2023-12-01T01:06:22.6234909Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI_interface.h:2,
2023-12-01T01:06:22.6235988Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_esolver/esolver_ks_lcao.h:12,
2023-12-01T01:06:22.6237400Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_hamilt_lcao/module_tddft/evolve_elec.h:6,
2023-12-01T01:06:22.6238630Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_elecstate/potentials/H_TDDFT_pw.cpp:5:
2023-12-01T01:06:22.6240578Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp: In function 'std::size_t Comm::Cereal_Func::align_stringstream(std::stringstream&)':
2023-12-01T01:06:22.6243041Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:37:46: error: 'Comm::MPI_Wrapper::char_contiguous' cannot be used as a function
2023-12-01T01:06:22.6250332Z    37 |   MPI_Wrapper::char_contiguous(exponent_align);
2023-12-01T01:06:22.6250795Z       |                                              ^
2023-12-01T01:06:22.6326527Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp: In function 'void Comm::Cereal_Func::mpi_send(const string&, std::size_t, int, int, ompi_communicator_t* const&)':
2023-12-01T01:06:22.6329588Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:53:110: error: 'Comm::MPI_Wrapper::char_contiguous' cannot be used as a function
2023-12-01T01:06:22.6331362Z    53 |   MPI_CHECK( MPI_Send  ( str.c_str(), str.size()>>exponent_align, MPI_Wrapper::char_contiguous(exponent_align), rank_recv, tag, mpi_comm ) );
2023-12-01T01:06:22.6332213Z       |                                                                                                              ^
2023-12-01T01:06:22.6333618Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:17:26: note: in definition of macro 'MPI_CHECK'
2023-12-01T01:06:22.6335414Z    17 | #define MPI_CHECK(x) if((x)!=MPI_SUCCESS) throw std::runtime_error(std::string(__FILE__)+" line "+std::to_string(__LINE__));
2023-12-01T01:06:22.6336155Z       |                          ^
2023-12-01T01:06:22.6337863Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp: In function 'void Comm::Cereal_Func::mpi_isend(const string&, std::size_t, int, int, ompi_communicator_t* const&, ompi_request_t*&)':
2023-12-01T01:06:22.6340519Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:79:111: error: 'Comm::MPI_Wrapper::char_contiguous' cannot be used as a function
2023-12-01T01:06:22.6342296Z    79 |   MPI_CHECK( MPI_Isend  ( str.c_str(), str.size()>>exponent_align, MPI_Wrapper::char_contiguous(exponent_align), rank_recv, tag, mpi_comm, &request ) );
2023-12-01T01:06:22.6343176Z       |                                                                                                               ^
2023-12-01T01:06:22.6344528Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:17:26: note: in definition of macro 'MPI_CHECK'
2023-12-01T01:06:22.6346050Z    17 | #define MPI_CHECK(x) if((x)!=MPI_SUCCESS) throw std::runtime_error(std::string(__FILE__)+" line "+std::to_string(__LINE__));
2023-12-01T01:06:22.6346790Z       |                          ^
2023-12-01T01:06:22.6347767Z In file included from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.h:48,
2023-12-01T01:06:22.6349852Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.hpp:9,
2023-12-01T01:06:22.6351536Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/Comm_Keys_31-gather.h:95,
2023-12-01T01:06:22.6352930Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/Comm_Assemble.h:8,
2023-12-01T01:06:22.6354322Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map.h:10,
2023-12-01T01:06:22.6355821Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/../comm/mix/Communicate_Tensors_Map_Judge.h:8,
2023-12-01T01:06:22.6357353Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.hpp:9,
2023-12-01T01:06:22.6358532Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx_Post_2D.h:58,
2023-12-01T01:06:22.6359649Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibRI/include/RI/physics/Exx.h:8,
2023-12-01T01:06:22.6360730Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI.h:14,
2023-12-01T01:06:22.6361764Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_ri/Exx_LRI_interface.h:2,
2023-12-01T01:06:22.6423678Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_esolver/esolver_ks_lcao.h:12,
2023-12-01T01:06:22.6425451Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_hamilt_lcao/module_tddft/evolve_elec.h:6,
2023-12-01T01:06:22.6426845Z                  from /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/source/module_elecstate/potentials/H_TDDFT_pw.cpp:5:
2023-12-01T01:06:22.6430637Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp: In function 'std::vector<char> Comm::Cereal_Func::mpi_recv(ompi_communicator_t* const&, MPI_Status&)':
2023-12-01T01:06:22.6433479Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:105:77: error: 'Comm::MPI_Wrapper::char_contiguous' cannot be used as a function
2023-12-01T01:06:22.6434972Z   105 |    const MPI_Datatype mpi_type = MPI_Wrapper::char_contiguous(exponent_align);
2023-12-01T01:06:22.6435601Z       |                                                                             ^
2023-12-01T01:06:22.6437374Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp: In function 'std::vector<char> Comm::Cereal_Func::mpi_mrecv(ompi_message_t*&, const MPI_Status&)':
2023-12-01T01:06:22.6439962Z /home/conda/feedstock_root/build_artifacts/abacus_1701392320555/work/deps/LibComm/include/Comm/Comm_Assemble/../Comm_Keys/../global/Cereal_Func.hpp:149:77: error: 'Comm::MPI_Wrapper::char_contiguous' cannot be used as a function
2023-12-01T01:06:22.6441445Z   149 |    const MPI_Datatype mpi_type = MPI_Wrapper::char_contiguous(exponent_align);
```

**Comment by njzjz** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
